### PR TITLE
Add a 'card' style theme

### PR DESCRIPTION
**Pull request by SimonMellerin**
Hi,

Don't know if it can interest you, but just in case, I've done a theme base on feedly-theme using card:

Capture d’écran de 2019-09-12 15-38-03

Cheers

### CODE REVIEW

**Comment by levito** [comment]
Hi @SimonMellerin,

thanks for the PR! It looks really nice and it's an interesting approach. But I'm afraid I won't merge it because it currently only works in expandable mode. And especially in that mode it feels a bit jumpy and unintuitive to me. Other modes break right now. So maybe I'll have a look into this later, maybe we can polish it so it works well in all display modes. For now, I'll close this PR.

However, I have cherry-picked the submodule url update from your PR :)

Cheers!

**Comment by SimonMellerin** [comment]
Indeed, I've been a bit too enthusiastic on this one.. ;)

Cheers !

**Comment by levito** [comment]
Hey @SimonMellerin, with tt-rss introducing a grid view, I could implement something similar to your PR. Please have a look at https://github.com/levito/tt-rss-feedly-theme/releases/tag/v2.8.0 if you're interested. The posts open as a layer to prevent jumping – this is also similar to how Feedly or Inoreader work.

Cheers, and happy Easter!

**Comment by SimonMellerin** [comment]
Nice !  This grid view was really missing from ttrss :) 
Thanks for the information.


Cheers
Simon

**Pull request closed without merging**
