### PR TITLE
Changes in UI

### PR DESCRIPTION
**Pull request by horosgrisa**
I fixed width of title of article 

**Before**
after25

**After**
after26

### CODE REVIEW

**Comment by levito** [comment]
Hi @horosgrisa, which browser (and version) are you using? In Chrome 44, Safari 8 and Firefox 39 on Mac it looks right. Your merge request would break the layout there.

**Comment by horosgrisa** [comment]
I use Firefox 39 in Arch Linux

**Comment by horosgrisa** [comment]
Chromium 44
**Before**
after28
**After**
after27

**Comment by levito** [comment]
Could you please check if you have set a custom stylesheet? (preferences => Interface: Customize stylesheet)

**Comment by horosgrisa** [comment]
@levito No, I don't have custom css.

**Comment by horosgrisa** [comment]
@levito Enabled plugins:
 af_unburn	Resolves feedburner and similar feed redirector URLs (requires CURL)
article_headline_toggle	Toggle article visibility by clicking on the headline 
feediron	Irons a feeds content to your needs
note	Adds support for setting article notes
no_url_hashes	Disable URL hash usage (e.g. #f=10, etc)
share	Share article by unique URL

none of them does not change the css

**Comment by levito** [comment]
Oh my, I did a similar fix on my local installation without pushing, so I didn't see the problem. Yours is better, so it's merged - thanks!

**Comment by horosgrisa** [comment]
OK

**Comment by onitreb** [comment]
Very cool. Thanks!

**Pull request merged**
